name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Set current date as env variable
        run: echo "NOW::$(date +'%H:%M:%S')" >> $GITHUB_ENV
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
      - name: PDF Release
        uses: softprops/action-gh-release@v1
        with:
          files: main.pdf
          tag_name: action_auto_release-${{ env.NOW }}
